# numpy

## numpy package import

In [3]:
import numpy as np

## numpy 배열 각 차원의 크기 

In [68]:
list1 = [1, 2, 3]
list1

[1, 2, 3]

In [69]:
a = np.array(list1)
a

array([1, 2, 3])

In [70]:
a.shape

(3,)

## numpy 배열 생성하는 방법
1. 파이썬 리스트 이용

In [15]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(b.shape)

(2, 4)


2. numpy 함수 이용

In [71]:
a = np.zeros((2,2)) # 0으로 배열 초기화
a

array([[0., 0.],
       [0., 0.]])

## numpy 함수

### 배열초기화

In [20]:
a = np.ones((3), dtype='int64') # 1로 배열 초기화
a

array([1, 1, 1], dtype=int64)

In [23]:
a = np.full((3),4, dtype='int64') # 사용자가 지정한 값으로 배열 초기화
a

array([4, 4, 4], dtype=int64)

### 배열구조 변경

In [62]:
a = np.array(range(12)).reshape((3,4)) # 0~11 원소를 3행 4열로
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a = np.array(range(12)).reshape((6, -1)) # 0~11원소 6행으로, 열 자동설정 ####
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

#### 3차원 배열

In [28]:
a = np.arange(24).reshape(2,3,4) # 3차원 배열 ####
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 배열 인덱싱 / 슬라이싱

#### 역 인덱스 슬라이스

In [65]:
lst = [[1, 2, 3], # 역인덱스 : -3, -2, -1열
        [4, 5, 6],
        [7, 8, 9]]
arr = np.array(lst)
a = arr [:, :-1] ##### 역 인덱스 슬라이스
a

array([[1, 2],
       [4, 5],
       [7, 8]])

#### 슬라이싱 테스트 위한 배열 생성

In [64]:
a = [0,1,2,3]
b = np.array ([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
a
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 다양한 인덱싱, 슬라이싱

In [42]:
print(a[:2])

[0, 1]


In [44]:
print(a[1:4:2]) # 1 ~ 4-1행, 2칸 간격####

[1, 3]


In [45]:
print(a[::-1]) # 역순 1칸 간격####

[3, 2, 1, 0]


In [46]:
print(b[0][1]) #배열변수명[행][열]

1


In [48]:
print(b[0,1]) #배열변수명[행,열]

1


In [49]:
print(b[:2]) # 0 ~ 2-1행

[[0 1 2 3]
 [4 5 6 7]]


In [50]:
print(b[:,0]) # 모든 행의 0열 # 배열변수명[행,열]

[0 4 8]


In [51]:
print(b[0,:]) # 0행의 모든 열

[0 1 2 3]


#### fancy indexing : 배열로 슬라이싱

In [52]:
print(b[[0,2],:]) # 0행과 2행(복수행)의 모든 열 #배열변수명[[행1,행2..],열]

[[ 0  1  2  3]
 [ 8  9 10 11]]


In [60]:
print(b[[2,0],:]) # 복수행 인덱스 입력 순서대로 출력됨####

[[ 8  9 10 11]
 [ 0  1  2  3]]


In [55]:
print(b[[0,2],[0,1]]) # 0행 0열, 2행 1열  #배열변수명[[행,열],[행,열]]####

[0 9]


#### boolean 방식의 fancy indexing : True, False 배열로 슬라이싱

In [57]:
b_5 = b > 5 # b배열의 원소들이 5보다 큰지####
b_5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
print(b_5) 

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [61]:
print(b[b_5]) # b_5의 조건 중 True에 해당하는 b의 원소들을 출력####

[ 6  7  8  9 10 11]


In [73]:
print(b[[0,2],[0,1]])

[0 9]


## Broadcasting

특정조건 충족시 자동으로 배열변환되어 연산
파이썬 대신 C로 벡터화하여 연산. 배열복사하지 않음.
빠른 속도, 높은 메모리 효율

In [74]:
a = [0,1,2,3]
c = np.arange(4)
c

array([0, 1, 2, 3])

In [75]:
print(c+1)

[1 2 3 4]


In [76]:
print(a+c)

[0 2 4 6]


In [78]:
d = np.zeros((2,2,4))
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [79]:
print(d+c)

[[[0. 1. 2. 3.]
  [0. 1. 2. 3.]]

 [[0. 1. 2. 3.]
  [0. 1. 2. 3.]]]


## Shape변환

In [80]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.split(a,2) # 행 기준으로 2개로 나눔

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [82]:
np.split(a,(1,3)) # 행을 0~1-1행과 1~3-1행 으로 나눔

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

#### 수평분할

In [83]:
splite1, splite2 = np.hsplit(a,2) # np.split(a,2,axis=1)

In [85]:
print("splite1");print(splite1); 

splite1
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [86]:
print("splite2"); print(splite2);

splite2
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### 수직분할

In [87]:
splite1, splite2 = np.vsplit(a,2) # np.split(a,2,axis=0)

In [88]:
print("splite1");print(splite1); 

splite1
[[0 1 2 3]
 [4 5 6 7]]


In [89]:
print("splite2"); print(splite2);

splite2
[[ 8  9 10 11]
 [12 13 14 15]]


## Stack연산 : 배열의 결합

In [123]:
a = np.array ([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 차원이 증가

In [124]:
stack0 = np.stack((a,a)) # axis=0 방향이 기본 # 수직결합
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [125]:
print(stack0.shape) # 2면 4행 4열로 차원이 증가함

(2, 4, 4)


In [107]:
stack1 = np.stack((a,a),axis=1) # 수평결합###
stack1

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15]]])

#### 차원증가없이 행 또는 열만 증가

In [105]:
print(np.vstack((a,a))) # 배열a과 배열a를 수직결합 _ 행 증가

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [106]:
print(np.hstack((a,a))) # 배열a과 배열a를 수평결합 _ 열 증가

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]


## faltten / ravel 연산 : 일차원구조로 변경

flatten()은 copy(원본데이터의 변화가 없음)
ravel()은 view (원본데이터 변화함)

In [96]:
a = np.array ([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [100]:
a.flatten()[0]=100
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [98]:
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [101]:
a.ravel()[0]=100 
a

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

## 배열 간 연산

In [108]:
a = np.array ([1, 2,])
a

array([1, 2])

In [109]:
b = np.array ([4, 5, 6])
b

array([4, 5, 6])

#### dot 함수 행열(matrix)의 곱(product)을 구함

In [118]:
lst1 = [[1,2],[3,4]]
lst1

[[1, 2], [3, 4]]

In [111]:
lst2 = [[1,2],[3,4]]
lst2

[[1, 2], [3, 4]]

In [119]:
a = np.array(lst1)
a

array([[1, 2],
       [3, 4]])

In [116]:
b = np.array(lst2)
b

array([[1, 2],
       [3, 4]])

In [117]:
c = np.dot(a,b)
c

array([[ 7, 10],
       [16, 24]])